# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MtM <- function(M) {
    .Call('_gprcpp_MtM', PACKAGE = 'gprcpp', M)
}

AtB <- function(A, B) {
    .Call('_gprcpp_AtB', PACKAGE = 'gprcpp', A, B)
}

A_solve <- function(M) {
    .Call('_gprcpp_A_solve', PACKAGE = 'gprcpp', M)
}

A_solve_B <- function(A, B) {
    .Call('_gprcpp_A_solve_B', PACKAGE = 'gprcpp', A, B)
}

